# 名前空間ごとに異なる設定を記載
namespace:
  namespace1:
    name: tenant-a
    port: 80
#デプロイメントの設定を記載
deployment:
  replicaCount: 1
  template:
    frontendImage: "nrt.ocir.io/nrcmxxv7sjse/ec_service_test:nodejs-stg-20250417-125215"
    backendImage: "nrt.ocir.io/nrcmxxv7sjse/ec_service_test:python-stg-20250417-125215"
    backendCommand: ["python", "-m", "http.server", "5000"]
#ラベルの設定を記載
selector:
  frontendLabel: frontend
  backendLabel: backend
#サービスの設定を記載
service:
  ports:
    protocol: TCP
    frontendTargetPort: 80
    backendPort: 5000
    backendTargetPort: 5000
