# 名前空間ごとに異なる設定を記載
namespace:
  namespace1:
    name: tenant-a
    port: 80
#デプロイメントの設定を記載
deployment:
  replicaCount: 1
  template:
    frontendImage: ""
    backendImage: ""
    backendCommand: ["python", "-m", "http.server", "5000"]
#ラベルの設定を記載
selector:
  frontendLabel: frontend
  backendLabel: backend
#サービスの設定を記載
service:
  ports:
    protocol: TCP
    frontendTargetPort: 80
    backendPort: 5000
    backendTargetPort: 5000
